### ISSUE TITLE
Could you convert the novels for the DS resolution

### ISSUE THREAD

**Issue by HumanKirby** [BASLQC/vnds#1]
Or is therean easy way to convert the high res packs to the DS resolution? The normal converters just do not want to work on my system. Much appreciated. Also, on a side note, was G_Senjou vnds development stoped?

**Comment by antonizoon** [comment]
Dunno, I didn't really feel like playing on a tiny ds screen anyway lol, so i never grabbed the low resolution packs. Try using this for batch resizing: http://www.imagemagick.org/script/mogrify.php

Pretty much everything incomplete should be considered stopped for good. But you can help continue their legacy by converting yourself.

**Comment by HumanKirby** [comment]
Thanks for the answer, gonna try the resizing. Also, since it seems like you used VNDS when there still was a wiki, do you know if there is a way to turn off the debug messages. They get quite annoying if they do not point out a real error.

Also, if I have internet at my place again, and the time to work on it, maybe I will work on G-Senjou.

**Comment by antonizoon** [comment]
I have no idea, I never used the DS version. BTW the Android version is much better and still available, that's what I depend on.

**Comment by HumanKirby** [comment]
Ok, so resizing works fine. I decided to work a bit with the source code of vnds, but it seems that even the lowest debuglevel does not deactivate this errormessage (which i fixed by letting it convert Umineko without the ps3 sprites, since it was just partcialy supported). Also, this "issue" is closed now.
