### ISSUE TITLE
Format of img.ini not supplied in porting guide

### ISSUE THREAD

**Issue by twocows** [BASLQC/vnds#5]
At [this page](https://github.com/BASLQC/vnds/wiki/Visual-Novel-Porting-Guide#Other_Files) on the wiki, the format used for the resolution isn't supplied (e.g., 640x480 possibly?). I downloaded a couple vnds projects but none of them had the img.ini file as reference.

**Comment by ajusa** [comment]
It should be of the format
```
width=800
height=600
```
That is from the fsn VNDS port.

**Comment by twocows** [comment]
Thanks!

**Comment by ajusa** [comment]
My [implementation of VNDS](https://github.com/ajusa/VNDS-LOVE) just checks for `width=` and `height=`. If someone else finds a different format that is used, feel free to update this issue!
