### ISSUE TITLE
Code.

### ISSUE THREAD

**Issue by poudink** [BASLQC/vnds#6]
VNDS is open source. The Android version may not be, but the original DS version is, so I think it's pretty weird that this repository is completely empty except for a readme file.

**Comment by antonizoon** [comment]
This repo was solely meant as a reconstruction of the Digital Haze wiki. 

However, you know what since the original VNDS source code is only available on the Internet Archive, and I don't see any other repo with it, I could rehost it here. Just need to find it again.

**Comment by ghost** [comment]
Find it here: https://github.com/ds-homebrew/vnds

**Comment by antonizoon** [comment]
Cool that there's still some development going on. This repo is solely meant to be a historical archive not to be edited. I can link the new repo as the place to go for new development.
